FROM node:22-alpine

WORKDIR /app

# Copiar package.json y package-lock.json (o yarn.lock si usas Yarn)
COPY package*.json ./

# Eliminar node_modules y package-lock.json para asegurar una instalación limpia
RUN rm -rf node_modules package-lock.json

# Instalar dependencias
RUN npm install

# Copiar el resto de los archivos del proyecto
COPY . .

EXPOSE 3000

CMD ["npm", "run", "dev"]