# Usar una imagen oficial de Node como base
FROM node:22

# Configurar el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copiar el 'package.json' y 'yarn.lock' (o 'package-lock.json') al directorio de trabajo
COPY package.json yarn.lock ./

# Limpiar la instalación previa y reinstalar dependencias
RUN rm -rf node_modules yarn.lock && yarn install

# Copiar el resto de los archivos del proyecto
COPY . .

# Exponer el puerto en el que Vite corre, usualmente es el 3000
EXPOSE 3000

# Comando para iniciar la aplicación en modo desarrollo
CMD ["yarn", "dev"]